process_SIF_dict = {
    "kfappointmentInfo": {
        "batchid": "",
        "batchno": "",
        "contractid": "9C2C70421FC56D23E053260811ACE26D",
        "contractno": "H202SC20011281",
        "contractname": "Davis-US-UMICH-27-Human-EukmRNAseq-WOBI-NVUS2019121644-rev-010720",
        "desc21": "",
        "desc24": "",
        "banlancemoney": "",
        "customercontractname": "",
        "desc22": "CP2020011600002",
        "corpname": "University of Michigan",
        "customeremail": "",
        "projectnum": "X202SC20011281",
        "projectname": "Davis-US-UMICH-27-Human-EukmRNAseq-WOBI-NVUS2019121644-rev-010720",
        "salesquono": "",
        "corpcontact": "Jerry",
        "corpphone": "-",
        "corpemail": "jerry.jie@novogeneusa.com",
        "backupcorpcontact": "",
        "backupcorpphone": "",
        "backupcorpemail": "",
        "desc23": "jerry.jie",
        "salesname": "Ruili Jie",
        "salesphone": "",
        "salesemail": "",
        "senddate": "",
        "wishtime": "",
        "desc10": "",
        "desc11": "",
        "desc12": "122703",
        "desc13": "04451B6C-4154-4343-83E2-43156684EFC1",
        "expresscompany": "FedEx-US",
        "expresnumber": "NSHIP201912164401",
        "transportationcond": "01",
        "desc14": "",
        "desc15": "",
        "desc16": "",
        "desc17": "",
        "desc18": "",
        "desc19": "",
        "desc20": "202",
        "sampletypearray": "",
        "samplecount": "",
        "desc7": "1",
        "desc8": "",
        "desc9": "02",
        "desc3": "",
        "desc4": "",
        "desc1": "",
        "desc2": "",
        "circulationtype": "1",
        "mixornot": "3",
        "mixexplain": "",
        "remark": "",
        "recordercode": "",
        "recorderdesc": "",
        "recordsystem": "NOVOGENE",
        "recordtime": "",
        "businesstype": "12",
        "status": "",
        "desc27": "N",
        "desc28": "",
        "disptatus": "",
        "auflag": "",
        "auditflag": "",
        "submitcorp": "024004",
        "corpcode": "",
        "corpdesc": "",
        "workflowid": "",
        "version": "",
        "iscreatedatainfo": "0",
        "outsourcingstatus":"no",
        "overseaflag":"",
        "packpool_cond":"",
        "pageflag":"zxmpcpage",
    }
}

sample_update_dict = {
    "kfsampleinfoInfos": [
        {
            "batchid": "",#
            "sampleid": "",#
            "businesstype": "12",
            "desc16": "LAA0038",
            "serialnumber": "",
            "desc1": "客户RNA",
            "buildlibrarytypecode": "S0005",
            "desc2": "",#
            "sampletype": "total RNA",
            "samplestatus": "溶于纯水",
            "desc5": "",#
            "speciestype": "",#
            "desc9": "",##
            "desc67": "",##
            "relationbatchcode": "",
            "desc4": "AA0015",
            "desc10": "Eukaryote mRNA-seq",
            "librariytype": "Regular mRNA library",
            "teststrategy": "PE150",
            "datas": "",#
            "dataunit": "",#
            "barcodesequence": "",
            "fragmentsize": "",
            "desc8": "",
            "isallgrind": "",
            "paraffinage": "",
            "paraffintype": "",
            "paraffinarea": "",
            "remark": "",
            "historysampleid": "",
            "historydesc3": "",
            "subprojectnum": "",#
            "subprojectdesc": "",#
            "concentration": "",
            "volume": ""
        },
    ]
}

process_SIF_dict_library = {
    "kfappointmentInfo": {
        "batchid": "",
        "batchno": "",
        "contractid": "9C79CB10F0333452E053260811AC1217",
        "contractno": "H202SC20011694",
        "contractname": "Davis-US-OSU-1-premade-1-hiseq-WOBI-NVUS2020011431",
        "desc21": "",
        "customercontractname": "",
        "desc24": "",
        "desc22": "CP2019081901187",
        "corpname": "The Ohio State University",
        "banlancemoney": "",
        "customeremail": "",
        "salesquono": "",
        "corpcontact": "jerry.jie",
        "corpphone": "-",
        "corpemail": "jerry.jie@novogeneusa.com",
        "backupcorpcontact": "",
        "backupcorpphone": "",
        "backupcorpemail": "",
        "desc23": "jerry.jie",
        "salesname": "Ruili Jie",
        "salesphone": "",
        "salesemail": "jerry.jie@novogeneusa.com",
        "projectnum": "X202SC20011694",
        "projectname": "Davis-US-OSU-1-premade-1-hiseq-WOBI-NVUS2020011431",
        "senddate": "",
        "wishtime": "",
        "desc10": "",
        "desc11": "",
        "desc12": "122703",
        "desc13": "04451B6C-4154-4343-83E2-43156684EFC1",
        "expresscompany": "FedEx",
        "expresnumber": "NSHIP202001143101",
        "transportationcond": "01",
        "desc14": "",
        "desc15": "",
        "desc16": "",
        "desc17": "",
        "desc18": "",
        "desc19": "",
        "desc20": "202",
        "sampletypearray": "",
        "samplecount": "",
        "desc1": "",
        "desc9": "02",
        "circulationtype": "",
        "desc6": "1",
        "desc7": "",
        "desc5": "0",
        "desc4": "",
        "desc25": "",
        "circulationtype_remark": "",
        "remark": "",
        "recordercode": "",
        "recorderdesc": "",
        "recordsystem": "NOVOGENE",
        "recordtime": "",
        "businesstype": "13",
        "status": "",
        "desc27": "N",
        "desc28": "",
        "disptatus": "",
        "auflag": "",
        "auditflag": "",
        "submitcorp": "024004",
        "corpcode": "",
        "corpdesc": "",
        "workflowid": "",
        "version": "",
        "iscreatedatainfo": "0",
        "outsourcingstatus": "no",
        "overseaflag": "",
        "packpool_cond": "",
        "pageflag": "zxmpcpage",
    }
}
